-- Deploy tdr:30-Contraints to pg

BEGIN;

ALTER TABLE "user" ALTER COLUMN "password" SET DATA TYPE TEXT ;
ALTER TABLE "quote" ALTER COLUMN "length" SET DATA TYPE INT ;
ALTER TABLE "quote" ALTER COLUMN "width" SET DATA TYPE INT ;
ALTER TABLE "quote" ALTER COLUMN "height" SET DATA TYPE INT ;
ALTER TABLE "quote" ALTER COLUMN "weight" SET DATA TYPE INT ;
ALTER TABLE "bill_address" ALTER COLUMN "postal_code" SET DATA TYPE TEXT ;
ALTER TABLE "sender_address" ALTER COLUMN "postal_code" SET DATA TYPE TEXT ;
ALTER TABLE "receiver_address" ALTER COLUMN "postal_code" SET DATA TYPE TEXT ;
ALTER TABLE "quote" ALTER COLUMN "ref_quote" SET DATA TYPE TEXT ;
ALTER TABLE "shipment" ALTER COLUMN "ref_shipment" SET DATA TYPE TEXT ;
ALTER TABLE "user" ALTER COLUMN "siret" SET DATA TYPE TEXT ;
ALTER TABLE "user" ALTER COLUMN "phone" SET DATA TYPE TEXT ;
ALTER TABLE "quote" DROP CONSTRAINT "nbr_pallets > 6" ;

DROP DOMAIN CHECK_PASSWORD ;

DROP DOMAIN POSTAL_CODE_FR ;

DROP DOMAIN PHONE ;

DROP DOMAIN SIRET ;

DROP DOMAIN INTERNAL_REF ;

DROP DOMAIN P_INT ;

COMMIT;
